apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-capstone
  namespace: udacity
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template: 
    metadata: 
      name: capstone-pod
      labels: 
        app: capstone
    spec:
      containers: # List
      - name: capstone-container
        image: 689660317632.dkr.ecr.us-east-2.amazonaws.com/udacity-cloud-devops-capstone:63c6c4b
        ports:
          - containerPort: 8000    
