apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-capstone-service
  namespace: udacity
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone-${version}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
